
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TimeTracker
      MYSQL_USER: TT
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


  web:
    build: .
    container_name: flask_app
    environment:
      - DATABASE_URI=mysql+pymysql://TT:password@db/TimeTracker
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
