"""descriptions added

Revision ID: 57bb319a86d7
Revises: eb0b2cae30d8
Create Date: 2024-12-11 22:52:08.694688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bb319a86d7'
down_revision = 'eb0b2cae30d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
