"""Added running timer boolean to Timer table

Revision ID: 950089422180
Revises: 4ea051fbb888
Create Date: 2024-11-29 00:30:29.088255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950089422180'
down_revision = '4ea051fbb888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_running', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_column('is_running')

    # ### end Alembic commands ###
