"""Timers Update

Revision ID: bbf6e4bc26f5
Revises: dd908750ef17
Create Date: 2024-11-26 10:57:08.076341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf6e4bc26f5'
down_revision = 'dd908750ef17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
